version: "3.7"

services:
  tidarr:
    image: cstaelen/tidarr:1.1.9
    restart: unless-stopped
    ports:
      - "${APP_SEBASA_TIDARR_PORT:-8484}:8484"
    environment:
      ADMIN_PASSWORD: ${APP_SEBASA_TIDARR_PASSWORD:-}
      PUID: ${APP_SEBASA_TIDARR_PUID:-1000}
      PGID: ${APP_SEBASA_TIDARR_PGID:-1000}
      UMASK: ${APP_SEBASA_TIDARR_UMASK:-0022}
    volumes:
      - ${APP_DATA_DIR}/config:/shared
      - ${APP_SEBASA_TIDARR_MUSIC_PATH:-/home/umbrel/media/music}:/music
    networks:
      default:
        ipv4_address: ${APP_SEBASA_TIDARR_IP}

networks:
  default:
    name: umbrel_main_network
    external: true
